const initialFamilyData = {
  p1: {
    id: "p1",
    name: "الغوث ولد الشيخ",
    gender: "male",
    dates: "",
    familyId: "p1",
    spouseIds: ["p2", "p6"],
    spouseId: "p2",
    childrenIds: ["p4", "p32", "p33", "p34", "p35", "p36", "p37", "p38", "p39"],
  },
  p2: {
    id: "p2",
    name: "صفية منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    familyId: "p3",
    childrenIds: ["p4", "p38", "p39"],
    spouseId: "p1",
    motherId: "p5",
  },
  p3: {
    id: "p3",
    name: "محمد سالم ولد زين",
    gender: "male",
    dates: "",
    familyId: "p3",
    spouseId: "p5",
    childrenIds: ["p2", "p6", "p7", "p8", "p9", "p10", "p11", "p12"],
    fatherId: "p7",
  },
  p4: {
    id: "p4",
    name: "محمد ولد الغوث",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p2",
    familyId: "p1",
    childrenIds: [],
  },
  p5: {
    id: "p5",
    name: "حاج منت ديدي",
    gender: "female",
    spouseId: "p3",
    childrenIds: ["p2", "p6", "p7", "p8", "p9", "p10", "p11", "p12"],
  },
  p6: {
    id: "p6",
    name: "تسلم منت محمد سالم",
    gender: "female",
    familyId: "p3",
    spouseId: "p1",
    fatherId: "p3",
    motherId: "p5",
    childrenIds: ["p32", "p33", "p34", "p35", "p36", "p37"],
  },
  p7: {
    id: "p7",
    name: "محمد الحسن ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p45",
    childrenIds: ["p3", "p27", "p28", "p29", "p30", "p31"],
  },
  p8: {
    id: "p8",
    name: "باه ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p44",
    childrenIds: ["p24", "p25", "p26"],
  },
  p9: {
    id: "p9",
    name: "محمد فال ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p43",
    childrenIds: ["p21", "p22", "p23"],
  },
  p10: {
    id: "p10",
    name: "خديج منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p40",
    childrenIds: ["p13", "p14", "p15", "p16"],
  },
  p11: {
    id: "p11",
    name: "أخت البنين منت محمد سال",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p41",
    childrenIds: ["p17", "p18"],
  },
  p12: {
    id: "p12",
    name: "هند منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p42",
    childrenIds: ["p19", "p20"],
  },
  p13: {
    id: "p13",
    name: "سعد",
    gender: "male",
    dates: "",
    fatherId: "p40",
    familyId: "p3",
    childrenIds: [],
    motherId: "p10",
  },
  p14: {
    id: "p14",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p40",
    familyId: "p3",
    childrenIds: [],
    motherId: "p10",
  },
  p15: {
    id: "p15",
    name: "تسلم",
    gender: "female",
    dates: "",
    fatherId: "p40",
    familyId: "p3",
    childrenIds: [],
    motherId: "p10",
  },
  p16: {
    id: "p16",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p40",
    familyId: "p3",
    childrenIds: [],
    motherId: "p10",
  },
  p17: {
    id: "p17",
    name: "أمين",
    gender: "male",
    dates: "",
    fatherId: "p41",
    familyId: "p3",
    childrenIds: [],
    motherId: "p11",
  },
  p18: {
    id: "p18",
    name: "الناه",
    gender: "male",
    dates: "",
    fatherId: "p41",
    familyId: "p3",
    childrenIds: [],
    motherId: "p11",
  },
  p19: {
    id: "p19",
    name: "باه",
    gender: "male",
    dates: "",
    fatherId: "p42",
    familyId: "p3",
    childrenIds: [],
    motherId: "p12",
  },
  p20: {
    id: "p20",
    name: "تسلم",
    gender: "male",
    dates: "",
    fatherId: "p42",
    familyId: "p3",
    childrenIds: [],
    motherId: "p12",
  },
  p21: {
    id: "p21",
    name: "عامر",
    gender: "male",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
    motherId: "p43",
  },
  p22: {
    id: "p22",
    name: "ديدي",
    gender: "male",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
    motherId: "p43",
  },
  p23: {
    id: "p23",
    name: "خديج",
    gender: "female",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
    motherId: "p43",
  },
  p24: {
    id: "p24",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
    motherId: "p44",
  },
  p25: {
    id: "p25",
    name: "مريم ",
    gender: "female",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
    motherId: "p44",
  },
  p26: {
    id: "p26",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
    motherId: "p44",
  },
  p27: {
    id: "p27",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
    motherId: "p45",
  },
  p28: {
    id: "p28",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
    motherId: "p45",
  },
  p29: {
    id: "p29",
    name: "صفية",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
    motherId: "p45",
  },
  p30: {
    id: "p30",
    name: "محمد فال",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
    motherId: "p45",
  },
  p31: {
    id: "p31",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
    motherId: "p45",
  },
  p32: {
    id: "p32",
    name: "الشيخ",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    spouseId: "p63",
    childrenIds: ["p57", "p58"],
  },
  p33: {
    id: "p33",
    name: "سدين",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    spouseId: "p62",
    childrenIds: ["p53", "p54", "p55", "p56"],
  },
  p34: {
    id: "p34",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    spouseId: "p61",
    childrenIds: ["p52"],
  },
  p35: {
    id: "p35",
    name: "مريم",
    gender: "female",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    spouseId: "p46",
    childrenIds: ["p47", "p48", "p49", "p50", "p51"],
  },
  p36: {
    id: "p36",
    name: "فاطمة ",
    gender: "female",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    childrenIds: [],
  },
  p37: {
    id: "p37",
    name: "مناي",
    gender: "female",
    dates: "",
    fatherId: "p1",
    motherId: "p6",
    familyId: "p3",
    spouseId: "p59",
    childrenIds: ["p60"],
  },
  p38: {
    id: "p38",
    name: "محمد محمود",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p2",
    familyId: "p3",
    childrenIds: [],
  },
  p39: {
    id: "p39",
    name: "فالة",
    gender: "female",
    dates: "",
    fatherId: "p1",
    motherId: "p2",
    familyId: "p3",
    childrenIds: [],
  },
  p40: {
    id: "p40",
    name: "الحسن ولد انجيه",
    gender: "male",
    dates: "",
    familyId: "p40",
    spouseId: "p10",
    childrenIds: ["p13", "p14", "p15", "p16"],
  },
  p41: {
    id: "p41",
    name: "الخليل ولد الجيد",
    gender: "male",
    familyId: "p41",
    spouseId: "p11",
    childrenIds: ["p17", "p18"],
  },
  p42: {
    id: "p42",
    name: "لمرابط ولد أكيبد",
    gender: "male",
    familyId: "p42",
    spouseId: "p12",
    childrenIds: ["p19", "p20"],
  },
  p43: {
    id: "p43",
    name: "النجاح منت ديدي",
    gender: "female",
    dates: "",
    familyId: "p43",
    spouseId: "p9",
    childrenIds: ["p21", "p22", "p23"],
  },
  p44: {
    id: "p44",
    name: "ساره منت ديدي",
    gender: "female",
    dates: "",
    familyId: "p44",
    spouseId: "p8",
    childrenIds: ["p24", "p25", "p26"],
  },
  p45: {
    id: "p45",
    name: "ميمون منت حي",
    gender: "female",
    dates: "",
    familyId: "p45",
    spouseId: "p7",
    childrenIds: ["p27", "p28", "p29", "p30", "p31"],
  },
  p46: {
    id: "p46",
    name: "محمد عبد الله ولد لولي",
    gender: "male",
    dates: "",
    familyId: "p46",
    spouseId: "p35",
    childrenIds: ["p47", "p48", "p49", "p50", "p51"],
  },
  p47: {
    id: "p47",
    name: "تسلم",
    gender: "female",
    dates: "",
    fatherId: "p46",
    motherId: "p35",
    familyId: "p3",
    childrenIds: [],
  },
  p48: {
    id: "p48",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p46",
    motherId: "p35",
    familyId: "p3",
    childrenIds: [],
  },
  p49: {
    id: "p49",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p46",
    motherId: "p35",
    familyId: "p3",
    childrenIds: [],
  },
  p50: {
    id: "p50",
    name: "حسن",
    gender: "male",
    dates: "",
    fatherId: "p46",
    motherId: "p35",
    familyId: "p3",
    childrenIds: [],
  },
  p51: {
    id: "p51",
    name: "نور",
    gender: "female",
    dates: "",
    fatherId: "p46",
    motherId: "p35",
    familyId: "p3",
    childrenIds: [],
  },
  p52: {
    id: "p52",
    name: "تسلم",
    gender: "male",
    dates: "",
    fatherId: "p34",
    motherId: "p61",
    familyId: "p3",
    childrenIds: [],
  },
  p53: {
    id: "p53",
    name: "محمد يحي",
    gender: "male",
    dates: "",
    fatherId: "p33",
    motherId: "p62",
    familyId: "p3",
    childrenIds: [],
  },
  p54: {
    id: "p54",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p33",
    motherId: "p62",
    familyId: "p3",
    childrenIds: [],
  },
  p55: {
    id: "p55",
    name: "مريم",
    gender: "female",
    dates: "",
    fatherId: "p33",
    motherId: "p62",
    familyId: "p3",
    childrenIds: [],
  },
  p56: {
    id: "p56",
    name: "محمد محمود",
    gender: "male",
    dates: "",
    fatherId: "p33",
    motherId: "p62",
    familyId: "p3",
    childrenIds: [],
  },
  p57: {
    id: "p57",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p32",
    motherId: "p63",
    familyId: "p3",
    childrenIds: [],
  },
  p58: {
    id: "p58",
    name: "يوسف",
    gender: "male",
    dates: "",
    fatherId: "p32",
    motherId: "p63",
    familyId: "p3",
    childrenIds: [],
  },
  p59: {
    id: "p59",
    name: "عادل",
    gender: "male",
    familyId: "p59",
    spouseId: "p37",
    childrenIds: ["p60"],
  },
  p60: {
    id: "p60",
    name: "عامر",
    gender: "male",
    dates: "",
    fatherId: "p59",
    motherId: "p37",
    familyId: "p3",
    childrenIds: [],
  },
  p61: {
    id: "p61",
    name: "هدى منت النعمان",
    gender: "female",
    familyId: "p61",
    spouseId: "p34",
    childrenIds: ["p52"],
  },
  p62: {
    id: "p62",
    name: "بيبت منت محمد ديد",
    gender: "female",
    familyId: "p62",
    spouseId: "p33",
    childrenIds: ["p53", "p54", "p55", "p56"],
  },
  p63: {
    id: "p63",
    name: "أمل",
    gender: "female",
    familyId: "p63",
    spouseId: "p32",
    childrenIds: ["p57", "p58"],
  },
  p70: {
    id: "p70",
    name: "زين",
    gender: "male",
    dates: "",
    familyId: "p70",
    childrenIds: ["p71", "p72", "p73", "p74"],
  },
  p71: {
    id: "p71",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p70",
    familyId: "p71",
    childrenIds: ["p75", "p76"],
  },
  p72: {
    id: "p72",
    name: "سيدي",
    gender: "male",
    dates: "",
    fatherId: "p70",
    familyId: "p70",
    childrenIds: [],
  },
  p73: {
    id: "p73",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p70",
    familyId: "p70",
    childrenIds: [],
  },
  p74: {
    id: "p74",
    name: "احمد",
    gender: "male",
    dates: "",
    fatherId: "p70",
    familyId: "p70",
    childrenIds: [],
  },
  p75: {
    id: "p75",
    name: "حي",
    gender: "male",
    dates: "",
    fatherId: "p71",
    familyId: "p75",
    childrenIds: ["p80", "p81", "p82", "p83", "p84", "p85", "p86", "p87"],
  },
  p76: {
    id: "p76",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p71",
    familyId: "p71",
    childrenIds: ["p77", "p78"],
  },
  p77: {
    id: "p77",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p76",
    familyId: "p71",
    childrenIds: [],
  },
  p78: {
    id: "p78",
    name: "إنجيه",
    gender: "male",
    dates: "",
    fatherId: "p76",
    familyId: "p71",
    childrenIds: ["p103", "p104"],
  },
  p79: {
    id: "p79",
    name: "خليه",
    gender: "male",
    dates: "",
    fatherId: "p87",
    familyId: "p75",
    childrenIds: ["p88", "p89"],
  },
  p80: {
    id: "p80",
    name: "سيدي",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: ["p90", "p91"],
  },
  p81: {
    id: "p81",
    name: "إمام",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: ["p92", "p93", "p100"],
  },
  p82: {
    id: "p82",
    name: "محمد اليدالي",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: ["p94", "p95"],
  },
  p83: {
    id: "p83",
    name: "السالم ",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: ["p96", "p97", "p98"],
  },
  p84: {
    id: "p84",
    name: "موسى",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: ["p99"],
  },
  p85: {
    id: "p85",
    name: "التاه",
    gender: "male",
    dates: "",
    fatherId: "p75",
    familyId: "p75",
    childrenIds: [],
  },
  p86: {
    id: "p86",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p75",
    childrenIds: [],
  },
  p87: {
    id: "p87",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p75",
    childrenIds: ["p79"],
  },
  p88: {
    id: "p88",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p79",
    familyId: "p75",
    childrenIds: ["p101", "p102"],
  },
  p89: {
    id: "p89",
    name: "الحسنان",
    gender: "male",
    dates: "",
    fatherId: "p79",
    familyId: "p75",
    childrenIds: [],
  },
  p90: {
    id: "p90",
    name: "مريم",
    gender: "female",
    dates: "",
    fatherId: "p80",
    familyId: "p75",
    childrenIds: [],
  },
  p91: {
    id: "p91",
    name: "عبد الله السالم",
    gender: "male",
    dates: "",
    fatherId: "p80",
    familyId: "p75",
    childrenIds: [],
  },
  p92: {
    id: "p92",
    name: "المختار",
    gender: "male",
    dates: "",
    fatherId: "p81",
    familyId: "p75",
    childrenIds: [],
  },
  p93: {
    id: "p93",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p81",
    familyId: "p75",
    childrenIds: [],
  },
  p94: {
    id: "p94",
    name: "فاطمة",
    gender: "female",
    dates: "",
    fatherId: "p82",
    familyId: "p75",
    childrenIds: [],
  },
  p95: {
    id: "p95",
    name: "مريم  ",
    gender: "female",
    dates: "",
    fatherId: "p82",
    familyId: "p75",
    childrenIds: [],
  },
  p96: {
    id: "p96",
    name: "محمد عال",
    gender: "male",
    dates: "",
    fatherId: "p83",
    familyId: "p75",
    childrenIds: [],
  },
  p97: {
    id: "p97",
    name: "احمد",
    gender: "male",
    dates: "",
    fatherId: "p83",
    familyId: "p75",
    childrenIds: [],
  },
  p98: {
    id: "p98",
    name: "الخيت",
    gender: "female",
    dates: "",
    fatherId: "p83",
    familyId: "p75",
    childrenIds: [],
  },
  p99: {
    id: "p99",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p84",
    familyId: "p75",
    childrenIds: [],
  },
  p100: {
    id: "p100",
    name: "احمديور",
    gender: "male",
    dates: "",
    fatherId: "p81",
    familyId: "p75",
    childrenIds: [],
  },
  p101: {
    id: "p101",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p88",
    familyId: "p75",
    childrenIds: [],
  },
  p102: {
    id: "p102",
    name: "محمد يحي",
    gender: "male",
    dates: "",
    fatherId: "p88",
    familyId: "p75",
    childrenIds: [],
  },
  p103: {
    id: "p103",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p78",
    familyId: "p71",
    childrenIds: [],
  },
  p104: {
    id: "p104",
    name: "اكَليكَم",
    gender: "male",
    dates: "",
    fatherId: "p78",
    familyId: "p71",
    childrenIds: [],
  },
};
