// =============================================
// FAMILY DATA
// All persons in the system
// =============================================

const initialFamilyData = {
  // Johnson Family
  p1: {
    id: "p1",
    name: "William Johnson",
    dates: "1920-1995",
    gender: "male",
    familyId: "p1",
    spouseId: "p50",
    childrenIds: ["p2", "p3", "p4"],
  },
  p2: {
    id: "p2",
    name: "Robert Johnson",
    dates: "1945-2020",
    gender: "male",
    familyId: "p1",
    fatherId: "p1",
    motherId: "p50",
    spouseId: "p51",
    childrenIds: ["p5", "p6"],
  },
  p3: {
    id: "p3",
    name: "Mary Johnson",
    dates: "1948-2018",
    gender: "female",
    familyId: "p1",
    fatherId: "p1",
    motherId: "p50",
    spouseId: "p52",
    childrenIds: ["p7", "p8"],
  },
  p4: {
    id: "p4",
    name: "Thomas Johnson",
    dates: "Born 1952",
    gender: "male",
    familyId: "p1",
    fatherId: "p1",
    motherId: "p50",
    spouseId: "p53",
    childrenIds: [],
  },
  p5: {
    id: "p5",
    name: "Michael Johnson",
    dates: "Born 1970",
    gender: "male",
    familyId: "p1",
    fatherId: "p2",
    motherId: "p51",
    spouseId: "p54",
    childrenIds: ["p9", "p10"],
  },
  p6: {
    id: "p6",
    name: "Sarah Johnson",
    dates: "Born 1973",
    gender: "female",
    familyId: "p1",
    fatherId: "p2",
    motherId: "p51",
    spouseId: "p55",
    childrenIds: [],
  },
  p7: {
    id: "p7",
    name: "James Williams",
    dates: "Born 1975",
    gender: "male",
    familyId: "p52",
    fatherId: "p52",
    motherId: "p3",
    childrenIds: [],
  },
  p8: {
    id: "p8",
    name: "Jennifer Williams",
    dates: "Born 1978",
    gender: "female",
    familyId: "p52",
    fatherId: "p52",
    motherId: "p3",
    childrenIds: [],
  },
  p9: {
    id: "p9",
    name: "Emma Johnson",
    dates: "Born 1998",
    gender: "female",
    familyId: "p1",
    fatherId: "p5",
    motherId: "p54",
  },
  p10: {
    id: "p10",
    name: "Liam Johnson",
    dates: "Born 2001",
    gender: "male",
    familyId: "p1",
    fatherId: "p5",
    motherId: "p54",
  },

  // Smith Family (Eleanor's family)
  p50: {
    id: "p50",
    name: "Eleanor Smith",
    dates: "1922-2000",
    gender: "female",
    familyId: "p60",
    fatherId: "p60",
    motherId: "p61",
    spouseId: "p1",
    childrenIds: ["p2", "p3", "p4"],
  },
  p60: {
    id: "p60",
    name: "Henry Smith",
    dates: "1895-1970",
    gender: "male",
    familyId: "p60",
    spouseId: "p61",
    childrenIds: ["p50", "p62"],
  },
  p61: {
    id: "p61",
    name: "Margaret Smith",
    dates: "1898-1975",
    gender: "female",
    familyId: "p60",
    spouseId: "p60",
    childrenIds: ["p50", "p62"],
  },
  p62: {
    id: "p62",
    name: "Dorothy Smith",
    dates: "1925-2005",
    gender: "female",
    familyId: "p60",
    fatherId: "p60",
    motherId: "p61",
  },

  // Williams Family (Patricia's family)
  p51: {
    id: "p51",
    name: "Patricia Williams",
    dates: "1948-2015",
    gender: "female",
    familyId: "p70",
    fatherId: "p70",
    motherId: "p71",
    spouseId: "p2",
    childrenIds: ["p5", "p6"],
  },
  p70: {
    id: "p70",
    name: "James Williams Sr.",
    dates: "1920-1990",
    gender: "male",
    familyId: "p70",
    spouseId: "p71",
    childrenIds: ["p51"],
  },
  p71: {
    id: "p71",
    name: "Ruth Williams",
    dates: "1924-1995",
    gender: "female",
    familyId: "p70",
    spouseId: "p70",
    childrenIds: ["p51"],
  },

  // Williams Family (George's family)
  p52: {
    id: "p52",
    name: "George Williams",
    dates: "1945-2010",
    gender: "male",
    familyId: "p52",
    spouseId: "p3",
    childrenIds: ["p7", "p8"],
  },

  // Davis Family (Barbara's family)
  p53: {
    id: "p53",
    name: "Barbara Davis",
    dates: "Born 1955",
    gender: "female",
    familyId: "p53",
    spouseId: "p4",
    childrenIds: [],
  },

  // Chen Family (Linda's family)
  p54: {
    id: "p54",
    name: "Linda Chen",
    dates: "Born 1972",
    gender: "female",
    familyId: "p54",
    spouseId: "p5",
    childrenIds: ["p9", "p10"],
  },

  // Miller Family (John's family)
  p55: {
    id: "p55",
    name: "John Miller",
    dates: "Born 1970",
    gender: "male",
    familyId: "p55",
    spouseId: "p6",
    childrenIds: [],
  },
};
