const initialFamilyData = {
  p1: {
    id: "p1",
    name: "الغوث ولد الشيخ",
    gender: "male",
    dates: "",
    familyId: "p1",
    spouseIds: ["p2", "p6"],
    spouseId: "p2",
    childrenIds: ["p4", "p32", "p33", "p34", "p35", "p36", "p37", "p38", "p39"],
  },
  p2: {
    id: "p2",
    name: "صفية منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    familyId: "p3",
    childrenIds: ["p4", "p38", "p39"],
    spouseId: "p1",
  },
  p3: {
    id: "p3",
    name: "محمد سالم ولد زين",
    gender: "male",
    dates: "",
    familyId: "p3",
    spouseId: "p5",
    childrenIds: ["p2", "p6", "p7", "p8", "p9", "p10", "p11", "p12"],
    fatherId: "p7",
  },
  p4: {
    id: "p4",
    name: "محمد ولد الغوث",
    gender: "male",
    dates: "",
    fatherId: "p1",
    motherId: "p2",
    familyId: "p1",
    childrenIds: [],
  },
  p5: {
    id: "p5",
    name: "حاج منت ديدي",
    gender: "female",
    spouseId: "p3",
    childrenIds: ["p6", "p2", "p7", "p8", "p9", "p10", "p11", "p12"],
  },
  p6: {
    id: "p6",
    name: "تسلم منت محمد سالم",
    gender: "female",
    familyId: "p3",
    spouseId: "p1",
    fatherId: "p3",
    motherId: "p5",
    childrenIds: ["p32", "p33", "p34", "p35", "p36", "p37"],
  },
  p7: {
    id: "p7",
    name: "محمد الحسن ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p45",
    childrenIds: ["p27", "p28", "p29", "p30", "p31"],
  },
  p8: {
    id: "p8",
    name: "باه ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p44",
    childrenIds: ["p24", "p25", "p26"],
  },
  p9: {
    id: "p9",
    name: "محمد فال ولد محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p43",
    childrenIds: ["p21", "p22", "p23"],
  },
  p10: {
    id: "p10",
    name: "خديج منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p40",
    childrenIds: ["p13", "p14", "p15", "p16"],
  },
  p11: {
    id: "p11",
    name: "أخت البنين منت محمد سال",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p41",
    childrenIds: ["p17", "p18"],
  },
  p12: {
    id: "p12",
    name: "هند منت محمد سالم",
    gender: "female",
    dates: "",
    fatherId: "p3",
    motherId: "p5",
    familyId: "p3",
    spouseId: "p42",
    childrenIds: ["p19", "p20"],
  },
  p13: {
    id: "p13",
    name: "سعد",
    gender: "male",
    dates: "",
    fatherId: "p10",
    familyId: "p3",
    childrenIds: [],
  },
  p14: {
    id: "p14",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p10",
    familyId: "p3",
    childrenIds: [],
  },
  p15: {
    id: "p15",
    name: "تسلم",
    gender: "female",
    dates: "",
    fatherId: "p10",
    familyId: "p3",
    childrenIds: [],
  },
  p16: {
    id: "p16",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p10",
    familyId: "p3",
    childrenIds: [],
  },
  p17: {
    id: "p17",
    name: "أمين",
    gender: "male",
    dates: "",
    fatherId: "p11",
    familyId: "p3",
    childrenIds: [],
  },
  p18: {
    id: "p18",
    name: "الناه",
    gender: "male",
    dates: "",
    fatherId: "p11",
    familyId: "p3",
    childrenIds: [],
  },
  p19: {
    id: "p19",
    name: "باه",
    gender: "male",
    dates: "",
    fatherId: "p12",
    familyId: "p3",
    childrenIds: [],
  },
  p20: {
    id: "p20",
    name: "تسلم",
    gender: "male",
    dates: "",
    fatherId: "p12",
    familyId: "p3",
    childrenIds: [],
  },
  p21: {
    id: "p21",
    name: "عامر",
    gender: "male",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
  },
  p22: {
    id: "p22",
    name: "ديدي",
    gender: "male",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
  },
  p23: {
    id: "p23",
    name: "خديج",
    gender: "female",
    dates: "",
    fatherId: "p9",
    familyId: "p3",
    childrenIds: [],
  },
  p24: {
    id: "p24",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
  },
  p25: {
    id: "p25",
    name: "مريم ",
    gender: "female",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
  },
  p26: {
    id: "p26",
    name: "محمد سالم",
    gender: "male",
    dates: "",
    fatherId: "p8",
    familyId: "p3",
    childrenIds: [],
  },
  p27: {
    id: "p27",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
  },
  p28: {
    id: "p28",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
  },
  p29: {
    id: "p29",
    name: "صفية",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
  },
  p30: {
    id: "p30",
    name: "محمد فال",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
  },
  p31: {
    id: "p31",
    name: "محمد عبد الله",
    gender: "male",
    dates: "",
    fatherId: "p7",
    familyId: "p3",
    childrenIds: [],
  },
  p32: {
    id: "p32",
    name: "الشيخ",
    gender: "male",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    spouseId: "p63",
    childrenIds: ["p57", "p58"],
  },
  p33: {
    id: "p33",
    name: "سدين",
    gender: "male",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    spouseId: "p62",
    childrenIds: ["p53", "p54", "p55", "p56"],
  },
  p34: {
    id: "p34",
    name: "الحسن",
    gender: "male",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    spouseId: "p61",
    childrenIds: ["p52"],
  },
  p35: {
    id: "p35",
    name: "مريم",
    gender: "female",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    spouseId: "p46",
    childrenIds: ["p47", "p48", "p49", "p50", "p51"],
  },
  p36: {
    id: "p36",
    name: "فاطمة ",
    gender: "female",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    childrenIds: [],
  },
  p37: {
    id: "p37",
    name: "مناي",
    gender: "female",
    dates: "",
    fatherId: "p6",
    motherId: "p1",
    familyId: "p3",
    spouseId: "p59",
    childrenIds: ["p60"],
  },
  p38: {
    id: "p38",
    name: "محمد محمود",
    gender: "male",
    dates: "",
    fatherId: "p2",
    motherId: "p1",
    familyId: "p3",
    childrenIds: [],
  },
  p39: {
    id: "p39",
    name: "فالة",
    gender: "female",
    dates: "",
    fatherId: "p2",
    motherId: "p1",
    familyId: "p3",
    childrenIds: [],
  },
  p40: {
    id: "p40",
    name: "الحسن ولد انجيه",
    gender: "male",
    dates: "",
    familyId: "p40",
    spouseId: "p10",
    childrenIds: ["p13", "p14", "p15", "p16"],
  },
  p41: {
    id: "p41",
    name: "الخليل ولد الجيد",
    gender: "male",
    familyId: "p41",
    spouseId: "p11",
    childrenIds: ["p17", "p18"],
  },
  p42: {
    id: "p42",
    name: "لمرابط ولد أكيبد",
    gender: "male",
    familyId: "p42",
    spouseId: "p12",
    childrenIds: ["p19", "p20"],
  },
  p43: {
    id: "p43",
    name: "النجاح منت ديدي",
    gender: "female",
    dates: "",
    familyId: "p43",
    spouseId: "p9",
    childrenIds: ["p21", "p22", "p23"],
  },
  p44: {
    id: "p44",
    name: "ساره منت ديدي",
    gender: "female",
    dates: "",
    familyId: "p44",
    spouseId: "p8",
    childrenIds: ["p24", "p25", "p26"],
  },
  p45: {
    id: "p45",
    name: "ميمون منت حي",
    gender: "female",
    dates: "",
    familyId: "p45",
    spouseId: "p7",
    childrenIds: ["p27", "p28", "p29", "p30", "p31"],
  },
  p46: {
    id: "p46",
    name: "محمد عبد الله ولد لولي",
    gender: "male",
    dates: "",
    familyId: "p46",
    spouseId: "p35",
    childrenIds: ["p47", "p48", "p49", "p50", "p51"],
  },
  p47: {
    id: "p47",
    name: "تسلم",
    gender: "female",
    dates: "",
    fatherId: "p35",
    motherId: "p46",
    familyId: "p3",
    childrenIds: [],
  },
  p48: {
    id: "p48",
    name: "محمد",
    gender: "male",
    dates: "",
    fatherId: "p35",
    motherId: "p46",
    familyId: "p3",
    childrenIds: [],
  },
  p49: {
    id: "p49",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p35",
    motherId: "p46",
    familyId: "p3",
    childrenIds: [],
  },
  p50: {
    id: "p50",
    name: "حسن",
    gender: "male",
    dates: "",
    fatherId: "p35",
    motherId: "p46",
    familyId: "p3",
    childrenIds: [],
  },
  p51: {
    id: "p51",
    name: "نور",
    gender: "female",
    dates: "",
    fatherId: "p35",
    motherId: "p46",
    familyId: "p3",
    childrenIds: [],
  },
  p52: {
    id: "p52",
    name: "تسلم",
    gender: "male",
    dates: "",
    fatherId: "p34",
    familyId: "p3",
    childrenIds: [],
  },
  p53: {
    id: "p53",
    name: "محمد يحي",
    gender: "male",
    dates: "",
    fatherId: "p33",
    familyId: "p3",
    childrenIds: [],
  },
  p54: {
    id: "p54",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p33",
    familyId: "p3",
    childrenIds: [],
  },
  p55: {
    id: "p55",
    name: "مريم",
    gender: "female",
    dates: "",
    fatherId: "p33",
    familyId: "p3",
    childrenIds: [],
  },
  p56: {
    id: "p56",
    name: "محمد محمود",
    gender: "male",
    dates: "",
    fatherId: "p33",
    familyId: "p3",
    childrenIds: [],
  },
  p57: {
    id: "p57",
    name: "الغوث",
    gender: "male",
    dates: "",
    fatherId: "p32",
    familyId: "p3",
    childrenIds: [],
  },
  p58: {
    id: "p58",
    name: "يوسف",
    gender: "male",
    dates: "",
    fatherId: "p32",
    familyId: "p3",
    childrenIds: [],
  },
  p59: {
    id: "p59",
    name: "عادل",
    gender: "male",
    familyId: "p59",
    spouseId: "p37",
    childrenIds: ["p60"],
  },
  p60: {
    id: "p60",
    name: "عامر",
    gender: "male",
    dates: "",
    fatherId: "p37",
    motherId: "p59",
    familyId: "p3",
    childrenIds: [],
  },
  p61: {
    id: "p61",
    name: "هدى منت النعمان",
    gender: "female",
    familyId: "p61",
    spouseId: "p34",
    childrenIds: ["p52"],
  },
  p62: {
    id: "p62",
    name: "بيبت منت محمد ديد",
    gender: "female",
    familyId: "p62",
    spouseId: "p33",
    childrenIds: ["p53", "p54", "p55", "p56"],
  },
  p63: {
    id: "p63",
    name: "أمل",
    gender: "female",
    familyId: "p63",
    spouseId: "p32",
    childrenIds: ["p57", "p58"],
  },
};
